on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kaynak kodu
        uses: actions/checkout@v3

      - name: GitHub Pages için hazırlık
        uses: actions/configure-pages@v4

      - name: Build artifact yükle
        uses: actions/upload-pages-artifact@v2
        with:
          path: . # Kök klasör

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: GitHub Pages'e dağıt
        id: deployment
        uses: actions/deploy-pages@v2
